source :rubygems

gem  'adva-core'
gem  'adva-blog'
gem  'adva-cache'
gem  'adva-categories'
gem  'adva-static'
gem  'adva-user'
gem  'adva-markup'

group :test do
  gem 'sqlite3-ruby', '1.2.5'
  gem "capybara", ">= 0.4.1.1"
  gem 'cucumber', '~> 0.10.2'
  gem 'cucumber-rails', '~> 0.4.1'
  gem 'thor'
  gem 'ruby-debug'
  gem 'mocha'
  gem 'fakefs', :require => 'fakefs/safe'
  gem 'test_declarative'
  gem 'database_cleaner', ' ~> 0.6.7'
  gem 'launchy'
  gem 'factory_girl', '1.3.2'
end
