source :rubygems

gem 'rails', '3.0.0.beta4'
gem 'gem_patching'
# gem 'resource_awareness'
gem 'inherited_resources', '1.1.2'
# gem 'inherited_resources', :path => '/Volumes/Users/sven/Development/lab/inherited_resources'
# gem 'inherited_resources', :git => 'http://github.com/josevalim/inherited_resources.git'